version: "3"

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: teshimapw
      POSTGRES_DB: prototype_database
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
