name: heroku build

on:
  push:
    branches: [feature/*]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_STAGING_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: ${GITHUB_REF#refs/heads/}
